version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data